FROM python:3.11-slim
WORKDIR /app
COPY requirements.txt .
RUN pip install -r requirements.txt
COPY scripts/ scripts/
ENTRYPOINT ["python"]
CMD ["scripts/amino_counter.py", "-i", "files/protein.fasta", "-o", "results/amino_stats.tsv"]
